<?php
/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Aize\Rma\ViewModel\RmaModel $lastOrdered */
$lastOrdered = $block->getData('view_model');

$orders = $lastOrdered->getOrders();
?>
    <h1 style="font-size:2em; "> Please select item(s) to continue RMA Request </h1>
<ul>
    <?php foreach ($orders as $order): ?>
        <?php $stockId = $lastOrdered->getStockId($order); ?>
        <li>Order Items:</li>
        <ul>
            <?php foreach ($order->getAllVisibleItems() as $item): ?>
            <?php $product = $item->getProduct(); ?>
            <label class="switch">
                <li>
                    <input type="checkbox">
                    <span class="slider round"></span>
                    <?php echo $item->getName();?> -
                    Price: <?php echo $item->getPrice() * $item->getQtyOrdered(); ?>$
                </li>
                <?php endforeach; ?>
            </label>
        </ul>
        <hr>
    <?php endforeach; ?>

    <button type="submit" value="Submit">Continue</button>
</ul>
