<?php /** @var \Aize\Rma\ViewModel\RmaRequestData $viewModel */ ?>
<?php $viewModel = $block->getData('viewModel'); ?>

<form action="<?= $block->getUrl('rma/index/submit') ?>" method="post" id="rma-request-form" data-mage-init='{"validation":{}}'>
    <?php if ($viewModel->getOrder() !== null): ?>
        <input type="hidden" name="order_id" value="<?= $block->escapeHtmlAttr($viewModel->getOrder()->getEntityId()) ?>">
        <div class="field required">
            <label for="item" class="label"><span><?= $block->escapeHtml(__('Order Item')) ?></span></label>
            <div class="control">
                <select name="order_item_id" id="item" class="input-text" data-validate="{required:true}">
                    <option value=""><?= $block->escapeHtml(__('Select Order Item')) ?></option>
                    <?php foreach ($viewModel->getOrderItems() as $item): ?>
                        <option value="<?= $block->escapeHtmlAttr($item->getItemId()) ?>"><?= $block->escapeHtml($item->getName()) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field required">
            <label for="quantity" class="label"><span><?= $block->escapeHtml(__('Quantity')) ?></span></label>
            <div class="control">
                <input type="number" name="quantity" id="quantity" value="" min="1" title="<?= $block->escapeHtmlAttr(__('Quantity')) ?>" class="input-text" data-validate="{required:true, 'validate-greater-than-zero':true}" data-msg-required="Please enter a quantity" data-msg-validate-greater-than-zero="Please enter a number greater than 0">
            </div>
        </div>
        <div class="field required">
            <label for="reason" class="label"><span><?= $block->escapeHtml(__('Return Reason')) ?></span></label>
            <div class="control">
                <textarea name="reason" id="reason" rows="5" title="<?= $block->escapeHtmlAttr(__('Return Reason')) ?>" class="input-text" data-validate="{required:true}" data-msg-required="Please enter a return reason"></textarea>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Submit RMA Request')) ?>">
                    <span><?= $block->escapeHtml(__('Submit RMA Request')) ?></span>
                </button>
            </div>
        </div>
    <?php else: ?>
        <p><?= $block->escapeHtml(__('Order not found. Please make sure the order_id parameter is correct.')) ?></p>
    <?php endif; ?>
</form>
