<?php
/** @var \Aize\Rma\Block\RmaHistory $block */
$rmaRequests = $block->getCustomerRmaRequests();
?>
<div class="rma-history">
    <?php if ($rmaRequests->getSize()): ?>
        <table class="data table table-rma-history">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('RMA ID')) ?></th>
                <th><?= $block->escapeHtml(__('Order ID')) ?></th>
                <th><?= $block->escapeHtml(__('Item Name')) ?></th>
                <th><?= $block->escapeHtml(__('Quantity')) ?></th>
                <th><?= $block->escapeHtml(__('Reason')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($rmaRequests as $request): ?>
                <tr>
                    <td><?= $block->escapeHtml($request->getId()) ?></td>
                    <td><?= $block->escapeHtml($request->getOrderId()) ?></td>
                    <td><?= $block->escapeHtml($block->getOrderItemName($request->getOrderItemId())) ?></td>
                    <td><?= $block->escapeHtml(number_format($request->getQuantity(), 0)) ?></td>
                    <td>  <?= $block->escapeHtml($request->getReason())?> </td>
                    <td>
                        <button type="button"> Check Status </button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p><?= $block->escapeHtml(__('You have no RMA requests.')) ?></p>
    <?php endif; ?>
</div>
